package com.example.bitecraftr.Model;

import androidx.annotation.NonNull;
import androidx.room.Embedded;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.io.Serializable;

/**
 * Represents a scheduled meal entity for the Scheduled_Meals table in the database.
 */
@Entity(tableName = "Scheduled_Meals" ,
        indices = {@Index(value = {"idMeal", "date"}, unique = true)})
public class ScheduledMeal implements Serializable {

    // Unique identifier for the planned meal, auto-generated by the database
    @NonNull
    @PrimaryKey(autoGenerate = true)
    private int ScheduledMealId;

    // The meal associated with this scheduled meal
    @Embedded
    private Meal meal;

    // The date on which the meal is planned
    private String date;

    /**
     * Constructor to create a ScheduledMeal with a specified meal and date.
     *
     * @param meal The meal to be scheduled.
     * @param date The date the meal is planned for.
     */
    public ScheduledMeal(Meal meal, String date) {
        this.meal = meal;
        this.date = date;
    }

    /**
     * Retrieves the meal associated with this scheduled meal.
     *
     * @return The meal.
     */
    public Meal getMeal() {
        return meal;
    }

    /**
     * Sets the meal for this scheduled meal.
     *
     * @param meal The meal to set.
     */
    public void setMeal(Meal meal) {
        this.meal = meal;
    }

    /**
     * Retrieves the date for this scheduled meal.
     *
     * @return The date as a String.
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the date for this scheduled meal.
     *
     * @param date The date to set.
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Retrieves the unique identifier for this scheduled meal.
     *
     * @return The ScheduledMealId.
     */
    public int getScheduledMealId() {
        return ScheduledMealId;
    }

    /**
     * Sets the unique identifier for this scheduled meal.
     *
     * @param ScheduledMealId The scheduled meal ID to set.
     */
    public void setScheduledMealId(int plannedMealId) {
        this.ScheduledMealId = plannedMealId;
    }
}
